fixes:
  - "kafkacow/::"

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: no

ignore:
  - "src/KafkaW/Consumer.cpp"
  - "src/KafkaW/Consumer.h"
  - "src/KafkaW/Producer.cpp"
  - "src/KafkaW/Producer.h"
  - "src/KafkaW/KafkaConfig.h"